services:
  - type: web
    plan: free
    name: matchmaking
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn matchmaking.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4