# Generated by Django 5.0.4 on 2024-04-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdetails',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='balanced',
            field=models.BooleanField(blank=True, choices=[('Balanceado', True), ('Desbalanceado', False)], null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='individual_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='goal_difference',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, choices=[('Victoria', 1), ('Empate', 0), ('Derrota', -1)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='team',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill',
            field=models.FloatField(null=True),
        ),
    ]
