# Generated by Django 5.0.4 on 2024-04-15 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_match_balanced_alter_match_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='field_size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='goal_difference',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-30), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='number_of_players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_one_goals',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_two_goals',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='assists',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='goals',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='individual_rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='team',
            field=models.IntegerField(blank=True, choices=[(1, 'Equipo 1'), (2, 'Equipo 2')], null=True),
        ),
    ]
