# Generated by Django 5.0.4 on 2024-04-19 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_match_field_size_alter_match_goal_difference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team_size',
            new_name='team_one_size',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.AddField(
            model_name='match',
            name='team_two_size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.IntegerField(blank=True, choices=[(1, 'Equipo 1'), (2, 'Equipo 2'), (0, 'Empate')], null=True),
        ),
    ]
