# Generated by Django 5.0.4 on 2024-04-19 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_team_size_match_team_one_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='number_of_players',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
