# Generated by Django 5.0.4 on 2024-04-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_positions_matchdetails_positions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchDetails',
            new_name='PlayerMatchDetails',
        ),
    ]
