# Generated by Django 5.0.4 on 2024-04-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_match_team_one_size_alter_match_team_two_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='number_of_players',
        ),
    ]
