# Generated by Django 5.0.4 on 2024-04-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('number_of_players', models.IntegerField()),
                ('team_size', models.IntegerField()),
                ('field_size', models.IntegerField()),
                ('result', models.CharField(max_length=15)),
                ('team_one_goals', models.IntegerField()),
                ('team_two_goals', models.IntegerField()),
                ('goal_difference', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('skill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('score', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.player')),
            ],
        ),
    ]
